title: First github page
author: Enrico Zangrando
email: enrizangri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am working on this site because it's part of the tutorial to learn how to use github pages.

# social links
twitter_username: EnricoZangrando # DO NOT include the @ character, or else the build will fail!
github_username:  Ezan777 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
